// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/proto/market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Trading pair, e.g., BTC/USD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataRequest) Reset() {
	*x = MarketDataRequest{}
	mi := &file_internal_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataRequest) ProtoMessage() {}

func (x *MarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataRequest.ProtoReflect.Descriptor instead.
func (*MarketDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDataRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type MarketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`   // Current price
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"` // Trading volume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataResponse) Reset() {
	*x = MarketDataResponse{}
	mi := &file_internal_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataResponse) ProtoMessage() {}

func (x *MarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataResponse.ProtoReflect.Descriptor instead.
func (*MarketDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *MarketDataResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDataResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketDataResponse) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_internal_proto_market_proto protoreflect.FileDescriptor

const file_internal_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/market.proto\x12\x06market\"+\n" +
	"\x11MarketDataRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"Z\n" +
	"\x12MarketDataResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume2[\n" +
	"\x11MarketDataService\x12F\n" +
	"\rGetMarketData\x12\x19.market.MarketDataRequest\x1a\x1a.market.MarketDataResponseB\x18Z\x16internal/market;marketb\x06proto3"

var (
	file_internal_proto_market_proto_rawDescOnce sync.Once
	file_internal_proto_market_proto_rawDescData []byte
)

func file_internal_proto_market_proto_rawDescGZIP() []byte {
	file_internal_proto_market_proto_rawDescOnce.Do(func() {
		file_internal_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_market_proto_rawDesc), len(file_internal_proto_market_proto_rawDesc)))
	})
	return file_internal_proto_market_proto_rawDescData
}

var file_internal_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_market_proto_goTypes = []any{
	(*MarketDataRequest)(nil),  // 0: market.MarketDataRequest
	(*MarketDataResponse)(nil), // 1: market.MarketDataResponse
}
var file_internal_proto_market_proto_depIdxs = []int32{
	0, // 0: market.MarketDataService.GetMarketData:input_type -> market.MarketDataRequest
	1, // 1: market.MarketDataService.GetMarketData:output_type -> market.MarketDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_market_proto_init() }
func file_internal_proto_market_proto_init() {
	if File_internal_proto_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_market_proto_rawDesc), len(file_internal_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_market_proto_goTypes,
		DependencyIndexes: file_internal_proto_market_proto_depIdxs,
		MessageInfos:      file_internal_proto_market_proto_msgTypes,
	}.Build()
	File_internal_proto_market_proto = out.File
	file_internal_proto_market_proto_goTypes = nil
	file_internal_proto_market_proto_depIdxs = nil
}
